apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-custom-properties
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-custom-properties
  template:
    metadata:
      labels:
        app: spring-custom-properties
        version: "v1"
    spec:
      containers:
        - name: spring-custom-properties
          image: iliaspap/spring-custom-properties:latest
          imagePullPolicy: Always #IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: actuator/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-custom-properties-service
spec:
  type: ClusterIP
  selector:
    app: spring-custom-properties
  ports:
    - name: http-api
      port: 8080
      targetPort: 8080